import type {
  Fabric,
  FabricCategory,
  GarmentModel,
  ModelCategory,
  Review,
  Style,
  Tailor,
  Vendor,
} from "@/lib/types";

// Local demo data — mirrors supabase/seed.sql. Used as a fallback so the whole
// catalog is browsable before the Supabase project is provisioned.

const img = (seed: string, w = 600, h = 600) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

// Real fabric swatches live in /public/fabrics (photographed catalogue).
const fabricImg = (n: number) => `/fabrics/${n}.jpg`;

// Real model photos live in /public/models — a person wearing each garment.
const modelImg = (slug: string) => `/models/${slug}.jpg`;

// Les galeries viennent des collections photographiées. Chaque groupe de
// lettres y est un même vêtement vu sous plusieurs angles : `a1` le vêtement
// seul, `a` porté, `a4` le détail. L'espace du dossier doit être encodé.
const homme = (...names: string[]) =>
  names.map((n) => `/collection%20homme/${n}.avif`);
const femme = (...names: string[]) =>
  names.map((n) => `/collection%20femme/${n}.avif`);
// Image principale d'un modèle femme, à partir d'un nom de fichier stable dans
// /public/collection femme (l'espace du dossier est encodé).
const femmeImg = (n: string) => `/collection%20femme/${n}.avif`;

export const FABRIC_CATEGORIES: FabricCategory[] = [
  { slug: "laine", name: "Laine", sort_order: 1 },
  { slug: "coton", name: "Coton", sort_order: 2 },
  { slug: "lin", name: "Lin", sort_order: 3 },
];

export const MODEL_CATEGORIES: ModelCategory[] = [
  { slug: "homme", name: "Homme", gender: "homme", sort_order: 1 },
  { slug: "femme", name: "Femme", gender: "femme", sort_order: 2 },
  { slug: "enfant", name: "Enfant", gender: "enfant", sort_order: 3 },
];

export const STYLES: Style[] = [
  { slug: "moderne", name: "Moderne", sort_order: 1 },
  { slug: "traditionnel", name: "Traditionnel", sort_order: 2 },
  { slug: "elegant", name: "Élégant", sort_order: 3 },
  { slug: "mariage", name: "Mariage", sort_order: 4 },
  { slug: "casual", name: "Casual", sort_order: 5 },
  { slug: "luxe", name: "Luxe", sort_order: 6 },
];

// Boutiques de tissu de démonstration (cf. VENDORS plus bas). Chaque tissu
// appartient à l'une d'elles, comme en production : c'est ce qui peuple la
// fiche publique du vendeur (`/vendeurs/[id]`).
const V = {
  hlm: "demo-vendor-hlm",
  touba: "demo-vendor-touba",
  khadi: "demo-vendor-khadi",
} as const;

export const FABRICS: Fabric[] = [
  {
    id: "demo-laine-vert-foret",
    vendor_id: V.touba,
    name: "Laine Mérinos Vert Forêt",
    category_slug: "laine",
    color: "Vert forêt",
    material: "Laine mérinos",
    price_per_meter: 12000,
    description: "Laine mérinos au tissage serré, teinte vert forêt profonde.",
    stock_meters: 60,
    image_url: fabricImg(1),
    is_active: true,
  },
  {
    id: "demo-tweed-gris-chine",
    vendor_id: V.touba,
    name: "Tweed Gris Chiné",
    category_slug: "laine",
    color: "Gris chiné",
    material: "Laine (tweed)",
    price_per_meter: 11000,
    description: "Tweed de laine gris chiné, texture chaude et structurée.",
    stock_meters: 45,
    image_url: fabricImg(2),
    is_active: true,
  },
  {
    id: "demo-coton-bleu-marine",
    vendor_id: V.hlm,
    name: "Coton Sergé Bleu Marine",
    category_slug: "coton",
    color: "Bleu marine",
    material: "Coton sergé",
    price_per_meter: 4500,
    description: "Sergé de coton bleu marine, mat et résistant, coupe nette.",
    stock_meters: 130,
    image_url: fabricImg(3),
    is_active: true,
  },
  {
    id: "demo-tweed-carreaux-beige",
    vendor_id: V.hlm,
    name: "Tweed à Carreaux Beige",
    category_slug: "laine",
    color: "Beige",
    material: "Laine (tweed)",
    price_per_meter: 12500,
    description: "Tweed à carreaux beige et bleu clair, esprit sport chic.",
    stock_meters: 40,
    image_url: fabricImg(4),
    is_active: true,
  },
  {
    id: "demo-laine-bleu-royal",
    vendor_id: V.touba,
    name: "Laine Bleu Royal",
    category_slug: "laine",
    color: "Bleu royal",
    material: "Laine",
    price_per_meter: 13000,
    description: "Laine bleu royal au micro-motif œil-de-perdrix, éclat discret.",
    stock_meters: 50,
    image_url: fabricImg(5),
    is_active: true,
  },
  {
    id: "demo-flanelle-bleu-ardoise",
    vendor_id: V.touba,
    name: "Flanelle Bleu Ardoise",
    category_slug: "laine",
    color: "Bleu ardoise",
    material: "Laine (flanelle)",
    price_per_meter: 11500,
    description: "Flanelle de laine bleu ardoise, toucher doux et fine rayure ton sur ton.",
    stock_meters: 55,
    image_url: fabricImg(6),
    is_active: true,
  },
  {
    id: "demo-popeline-blanche",
    vendor_id: V.khadi,
    name: "Popeline Blanche",
    category_slug: "coton",
    color: "Blanc",
    material: "Coton",
    price_per_meter: 3800,
    description: "Popeline de coton blanche, indispensable pour chemises habillées.",
    stock_meters: 160,
    image_url: fabricImg(7),
    is_active: true,
  },
  {
    id: "demo-popeline-gris-perle",
    vendor_id: V.khadi,
    name: "Popeline Gris Perle",
    category_slug: "coton",
    color: "Gris perle",
    material: "Coton",
    price_per_meter: 3800,
    description: "Popeline de coton gris perle, lumineuse et facile à porter.",
    stock_meters: 140,
    image_url: fabricImg(8),
    is_active: true,
  },
  {
    id: "demo-serge-bordeaux",
    vendor_id: V.hlm,
    name: "Sergé Bordeaux",
    category_slug: "laine",
    color: "Bordeaux",
    material: "Laine sergé",
    price_per_meter: 10500,
    description: "Sergé de laine bordeaux au tissage diagonal, profond et élégant.",
    stock_meters: 50,
    image_url: fabricImg(9),
    is_active: true,
  },
  {
    id: "demo-seersucker-vert",
    vendor_id: V.hlm,
    name: "Seersucker Rayé Vert",
    category_slug: "coton",
    color: "Vert",
    material: "Coton (seersucker)",
    price_per_meter: 5000,
    description: "Seersucker de coton à rayures vertes, gaufré et respirant pour la chaleur.",
    stock_meters: 90,
    image_url: fabricImg(10),
    is_active: true,
  },
  {
    id: "demo-lin-terracotta",
    vendor_id: V.khadi,
    name: "Lin Terracotta",
    category_slug: "lin",
    color: "Terracotta",
    material: "Lin",
    price_per_meter: 6500,
    description: "Lin terracotta au grain naturel, léger et respirant.",
    stock_meters: 80,
    image_url: fabricImg(11),
    is_active: true,
  },
  {
    id: "demo-laine-prune",
    vendor_id: V.touba,
    name: "Laine Prune",
    category_slug: "laine",
    color: "Prune",
    material: "Laine",
    price_per_meter: 12000,
    description: "Laine unie couleur prune, tombé souple et raffiné.",
    stock_meters: 45,
    image_url: fabricImg(12),
    is_active: true,
  },
  {
    id: "demo-lin-vert-olive",
    vendor_id: V.khadi,
    name: "Lin Vert Olive",
    category_slug: "lin",
    color: "Vert olive",
    material: "Lin",
    price_per_meter: 6500,
    description: "Lin vert olive au grain naturel, idéal pour les tenues d'été.",
    stock_meters: 75,
    image_url: fabricImg(13),
    is_active: true,
  },
  {
    id: "demo-popeline-rose-poudre",
    vendor_id: V.khadi,
    name: "Popeline Rose Poudré",
    category_slug: "coton",
    color: "Rose",
    material: "Coton",
    price_per_meter: 3800,
    description: "Popeline de coton rose poudré, douce et lumineuse.",
    stock_meters: 120,
    image_url: fabricImg(14),
    is_active: true,
  },
];

const MODELS_RAW: Omit<GarmentModel, "slug">[] = [
  {
    id: "demo-grand-boubou",
    tailor_id: null,
    name: "Grand Boubou",
    category_slug: "homme",
    description: "Ample tenue traditionnelle en trois pièces, symbole d'élégance.",
    difficulty: "moyen",
    avg_days: 10,
    image_url: modelImg("grand-boubou"),
    is_active: true,
    photos: homme("a1", "a", "a2", "a4"),
  },
  {
    id: "demo-kaftan",
    tailor_id: null,
    name: "Kaftan",
    category_slug: "homme",
    description: "Tunique longue et fluide, confortable et raffinée.",
    difficulty: "facile",
    avg_days: 7,
    image_url: modelImg("kaftan"),
    is_active: true,
    photos: homme("c1", "c", "c2"),
  },
  {
    id: "demo-chemise",
    tailor_id: null,
    name: "Chemise Africaine",
    category_slug: "homme",
    description: "Chemise à motifs, coupe moderne ou classique.",
    difficulty: "facile",
    avg_days: 5,
    image_url: modelImg("chemise"),
    is_active: true,
    photos: homme("b1", "b", "b2", "b3", "chemise"),
  },
  {
    id: "demo-costume",
    tailor_id: null,
    name: "Costume",
    category_slug: "homme",
    description: "Costume sur mesure, veste et pantalon.",
    difficulty: "difficile",
    avg_days: 14,
    image_url: modelImg("costume"),
    is_active: true,
    photos: homme("k1", "k", "k2"),
  },
  {
    id: "demo-relax",
    tailor_id: null,
    name: "Relax",
    category_slug: "homme",
    description:
      "Tenue décontractée : tunique fluide et pantalon confort, coupe ample facile à vivre, du week-end aux moments détente.",
    difficulty: "facile",
    avg_days: 6,
    image_url: "/collection%20homme/e.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-ensemble-bazin",
    tailor_id: null,
    name: "Ensemble Bazin",
    category_slug: "homme",
    description:
      "Ensemble deux-pièces en bazin riche : haut brodé et pantalon assorti, l'élégance africaine du quotidien aux grandes occasions.",
    difficulty: "moyen",
    avg_days: 9,
    image_url: "/collection%20homme/senegalais.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-agbada",
    tailor_id: null,
    name: "Agbada",
    category_slug: "homme",
    description:
      "Grande robe d'apparat brodée, portée sur un boubou et un pantalon — la pièce maîtresse des cérémonies ouest-africaines.",
    difficulty: "difficile",
    avg_days: 12,
    image_url: "/collection%20homme/nigerien.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-kaftan-brode",
    tailor_id: null,
    name: "Kaftan Brodé",
    category_slug: "homme",
    description:
      "Kaftan tunique longue rehaussée de broderies au col et au plastron, raffiné pour les fêtes et le vendredi.",
    difficulty: "moyen",
    avg_days: 8,
    image_url: "/collection%20homme/katan%20ghana.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-tenue-ceremonie",
    tailor_id: null,
    name: "Tenue de Cérémonie",
    category_slug: "homme",
    description:
      "Grand ensemble de cérémonie, broderie riche et finitions soignées, pour mariages, baptêmes et grandes fêtes.",
    difficulty: "difficile",
    avg_days: 12,
    image_url: "/collection%20homme/presi.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-costume-africain",
    tailor_id: null,
    name: "Costume Africain",
    category_slug: "homme",
    description:
      "Costume à coupe africaine — veste col Mao ou Senghor et pantalon — l'allure business, en tissu local ou importé.",
    difficulty: "difficile",
    avg_days: 12,
    image_url: "/collection%20homme/bureau.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-veste-africaine",
    tailor_id: null,
    name: "Veste Africaine",
    category_slug: "homme",
    description:
      "Veste-blazer d'inspiration africaine, à porter sur une chemise ou un tee-shirt pour un style habillé décontracté.",
    difficulty: "moyen",
    avg_days: 8,
    image_url: "/collection%20homme/paxy.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-gilet",
    tailor_id: null,
    name: "Gilet",
    category_slug: "homme",
    description:
      "Gilet sans manches, brodé ou uni, porté seul ou sur une chemise pour structurer la silhouette.",
    difficulty: "facile",
    avg_days: 5,
    image_url: "/collection%20homme/gilet.avif",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-pantalon",
    tailor_id: null,
    name: "Pantalon",
    category_slug: "homme",
    description:
      "Pantalon sur mesure — droit, cintré ou large façon saroual — en tissu au choix, seul ou pour compléter un ensemble.",
    difficulty: "facile",
    avg_days: 5,
    image_url: "/collection%20homme/pantalon.avif",
    is_active: true,
    photos: homme("pantalon", "panta"),
  },
  {
    id: "demo-dashiki",
    tailor_id: null,
    name: "Dashiki",
    category_slug: "homme",
    description:
      "Tunique ample à enfiler, col brodé et motifs colorés — l'esprit panafricain, décontracté et festif.",
    difficulty: "facile",
    avg_days: 5,
    image_url: "/collection%20homme/e.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-baye-lahat",
    tailor_id: null,
    name: "Baye Lahat",
    category_slug: "homme",
    description:
      "Grand boubou traditionnel à la coupe Baye Lahat, ample et solennel, prisé pour les grandes cérémonies religieuses.",
    difficulty: "difficile",
    avg_days: 12,
    image_url: "/collection%20homme/a3.avif",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-thiaya",
    tailor_id: null,
    name: "Thiaya",
    category_slug: "homme",
    description:
      "Pantalon traditionnel africain, taille haute et coupe ample, porté sous le boubou ou le kaftan.",
    difficulty: "facile",
    avg_days: 5,
    image_url: "/collection%20homme/d.avif",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-robe",
    tailor_id: null,
    name: "Robe",
    category_slug: "femme",
    description: "Robe sur mesure, du quotidien à la cérémonie.",
    difficulty: "moyen",
    avg_days: 9,
    image_url: modelImg("robe"),
    is_active: true,
    photos: femme("w", "w1", "w2"),
  },
  {
    id: "demo-ensemble",
    tailor_id: null,
    name: "Ensemble",
    category_slug: "femme",
    description: "Ensemble coordonné haut et bas.",
    difficulty: "moyen",
    avg_days: 8,
    image_url: modelImg("ensemble"),
    is_active: true,
    photos: femme("o", "o1"),
  },
  {
    id: "demo-jupe",
    tailor_id: null,
    name: "Jupe",
    category_slug: "femme",
    description: "Jupe sur mesure, plusieurs longueurs et coupes.",
    difficulty: "facile",
    avg_days: 5,
    image_url: modelImg("jupe"),
    is_active: true,
    photos: femme("q", "q1"),
  },
  {
    id: "demo-boubou-femme",
    tailor_id: null,
    name: "Boubou Femme",
    category_slug: "femme",
    description: "Boubou féminin élégant, brodé ou uni.",
    difficulty: "moyen",
    avg_days: 10,
    image_url: modelImg("boubou-femme"),
    is_active: true,
    photos: femme("f2", "f1", "f3"),
  },
  {
    id: "demo-grande-robe",
    tailor_id: null,
    name: "Grande Robe",
    category_slug: "femme",
    description:
      "Grande robe longue d'apparat, ample et fluide, brodée au col et au plastron — l'élégance des grandes occasions.",
    difficulty: "moyen",
    avg_days: 10,
    image_url: femmeImg("grande-robe"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-gilet-femme",
    tailor_id: null,
    name: "Gilet",
    category_slug: "femme",
    description:
      "Gilet sans manches, brodé ou uni, porté seul ou sur une chemise pour structurer la silhouette.",
    difficulty: "facile",
    avg_days: 4,
    image_url: femmeImg("gilet"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-chemise-femme",
    tailor_id: null,
    name: "Chemise",
    category_slug: "femme",
    description:
      "Chemise sur mesure, coupe droite ou cintrée, en tissu au choix — du bureau au quotidien.",
    difficulty: "facile",
    avg_days: 5,
    image_url: femmeImg("chemise"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-pantalon-large",
    tailor_id: null,
    name: "Pantalon Large",
    category_slug: "femme",
    description:
      "Pantalon large et fluide à taille haute, tombé ample et confortable, seul ou pour compléter un ensemble.",
    difficulty: "facile",
    avg_days: 5,
    image_url: femmeImg("pantalon-large"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-robe-soiree",
    tailor_id: null,
    name: "Robe de Soirée",
    category_slug: "femme",
    description:
      "Robe de soirée longue, coupe sculptée et finitions raffinées, pour cérémonies et grandes réceptions.",
    difficulty: "difficile",
    avg_days: 12,
    image_url: femmeImg("robe-soiree"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-robe-coupee",
    tailor_id: null,
    name: "Robe Coupée",
    category_slug: "femme",
    description:
      "Robe à coupe structurée, cintrée à la taille, moderne et ajustée — du bureau à la sortie.",
    difficulty: "moyen",
    avg_days: 8,
    image_url: femmeImg("robe-coupee"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-tailleur-pantalon",
    tailor_id: null,
    name: "Tailleur Pantalon",
    category_slug: "femme",
    description:
      "Tailleur deux-pièces — veste ajustée et pantalon assorti — l'allure business au féminin.",
    difficulty: "difficile",
    avg_days: 12,
    image_url: femmeImg("tailleur-pantalon"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-veste-femme",
    tailor_id: null,
    name: "Veste",
    category_slug: "femme",
    description:
      "Veste-blazer sur mesure, à porter sur une chemise ou une robe pour un style habillé décontracté.",
    difficulty: "moyen",
    avg_days: 8,
    image_url: femmeImg("veste"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-bureau-femme",
    tailor_id: null,
    name: "Tenue de Bureau",
    category_slug: "femme",
    description:
      "Ensemble professionnel sobre et élégant, coupe nette et tissu structuré, pensé pour le travail.",
    difficulty: "moyen",
    avg_days: 8,
    image_url: femmeImg("bureau"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-ceremonie-femme",
    tailor_id: null,
    name: "Tenue de Cérémonie",
    category_slug: "femme",
    description:
      "Grande tenue de cérémonie, broderie riche et finitions soignées, pour mariages, baptêmes et grandes fêtes.",
    difficulty: "difficile",
    avg_days: 12,
    image_url: femmeImg("ceremonie"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-thiaya-femme",
    tailor_id: null,
    name: "Thiaya",
    category_slug: "femme",
    description:
      "Thiaya — tenue traditionnelle africaine deux-pièces : haut ajusté et jupe droite taille basse, brodée, élégante du quotidien aux fêtes.",
    difficulty: "moyen",
    avg_days: 9,
    image_url: femmeImg("thiaya"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-boubou-enfant",
    tailor_id: null,
    name: "Boubou Enfant",
    category_slug: "enfant",
    description: "Boubou pour enfant, coupe confortable.",
    difficulty: "facile",
    avg_days: 5,
    image_url: modelImg("boubou-enfant"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-ensemble-enfant",
    tailor_id: null,
    name: "Ensemble Enfant",
    category_slug: "enfant",
    description: "Ensemble assorti pour enfant.",
    difficulty: "facile",
    avg_days: 5,
    image_url: modelImg("ensemble-enfant"),
    is_active: true,
    photos: [],
  },

  // --- Créations signées des tailleurs de démo -----------------------------
  // Contrairement au catalogue plateforme ci-dessus (`tailor_id` null), ces
  // modèles appartiennent à un tailleur : ils peuplent sa fiche publique
  // (`/tailleurs/[id]`, cf. `getModelsByTailor`) et son dashboard « Mes
  // créations » (`getTailorModels`). Les commander verrouille leur auteur
  // comme tailleur de la commande.
  {
    id: "demo-fatou-boubou-ceremonie",
    tailor_id: "demo-tailor-fatou",
    name: "Grand Boubou de Cérémonie",
    category_slug: "homme",
    description:
      "Grand boubou d'apparat brodé main, coupe ample et solennelle — la signature cérémonie de l'atelier.",
    difficulty: "difficile",
    avg_days: 12,
    image_url: "/collection%20homme/presi.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-fatou-bazin-brode",
    tailor_id: "demo-tailor-fatou",
    name: "Ensemble Bazin Brodé",
    category_slug: "homme",
    description:
      "Ensemble deux-pièces en bazin riche, haut brodé et pantalon assorti, teinture et broderie soignées.",
    difficulty: "moyen",
    avg_days: 9,
    image_url: "/collection%20homme/senegalais.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-fatou-ceremonie-femme",
    tailor_id: "demo-tailor-fatou",
    name: "Tenue de Cérémonie Femme",
    category_slug: "femme",
    description:
      "Grande tenue de cérémonie brodée, finitions raffinées, pour mariages, baptêmes et grandes fêtes.",
    difficulty: "difficile",
    avg_days: 12,
    image_url: femmeImg("ceremonie"),
    is_active: true,
    photos: [],
  },
  {
    id: "demo-modou-costume-africain",
    tailor_id: "demo-tailor-modou",
    name: "Costume Africain Moderne",
    category_slug: "homme",
    description:
      "Costume à coupe africaine, veste col Mao et pantalon assorti — l'allure business, façon moderne.",
    difficulty: "difficile",
    avg_days: 14,
    image_url: "/collection%20homme/bureau.jpg",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-modou-chemise",
    tailor_id: "demo-tailor-modou",
    name: "Chemise Cintrée à Motifs",
    category_slug: "homme",
    description:
      "Chemise sur mesure à coupe cintrée, motifs contemporains, du bureau au quotidien.",
    difficulty: "facile",
    avg_days: 5,
    image_url: "/collection%20homme/chemise.avif",
    is_active: true,
    photos: [],
  },
  {
    id: "demo-awa-boubou-femme",
    tailor_id: "demo-tailor-awa",
    name: "Boubou Femme Brodé",
    category_slug: "femme",
    description:
      "Boubou féminin élégant à broderie fine au col et au plastron, finitions luxe.",
    difficulty: "moyen",
    avg_days: 10,
    image_url: femmeImg("f2"),
    is_active: true,
    photos: femme("f2", "f1", "f3"),
  },
  {
    id: "demo-awa-ensemble-femme",
    tailor_id: "demo-tailor-awa",
    name: "Ensemble Brodé Femme",
    category_slug: "femme",
    description:
      "Ensemble coordonné haut et bas, broderie fine et tissu structuré, pour les grandes occasions.",
    difficulty: "moyen",
    avg_days: 8,
    image_url: femmeImg("o"),
    is_active: true,
    photos: femme("o", "o1"),
  },
  {
    id: "demo-ibrahima-boubou",
    tailor_id: "demo-tailor-ibrahima",
    name: "Grand Boubou Traditionnel",
    category_slug: "homme",
    description:
      "Grand boubou traditionnel, coupe généreuse et travail soigné, prêt en quelques jours.",
    difficulty: "moyen",
    avg_days: 8,
    image_url: "/collection%20homme/a.avif",
    is_active: true,
    photos: homme("a1", "a", "a2", "a4"),
  },
  {
    id: "demo-ibrahima-kaftan",
    tailor_id: "demo-tailor-ibrahima",
    name: "Kaftan Traditionnel",
    category_slug: "homme",
    description:
      "Kaftan tunique longue et fluide, confortable et raffiné, dans le respect de la coupe traditionnelle.",
    difficulty: "facile",
    avg_days: 6,
    image_url: "/collection%20homme/c.avif",
    is_active: true,
    photos: homme("c1", "c", "c2"),
  },
];

// Le slug est dérivé de l'`id` (`demo-grand-boubou` → `grand-boubou`) pour que
// les fixtures parlent le même langage que la base : en prod, ces mêmes slugs
// sont posés sur les lignes seedées (cf. `supabase/seed.sql`). C'est ce qui
// permet aux pages dédiées de résoudre un modèle par slug dans les deux modes.
export const MODELS: GarmentModel[] = MODELS_RAW.map((m) => ({
  ...m,
  slug: m.id.replace(/^demo-/, ""),
}));

export const TAILORS: Tailor[] = [
  {
    id: "demo-tailor-fatou",
    shop_name: "Atelier Fatou Couture",
    bio: "Spécialiste des tenues de cérémonie et du bazin brodé, 12 ans d'expérience.",
    city: "Dakar",
    base_price: 15000,
    avg_delivery_days: 7,
    free_delivery: true,
    cover_url: img("atelierfatou"),
    rating: 4.8,
    rating_count: 126,
    is_active: true,
    is_suspended: false,
    suspension_reason: null,
    is_certified: true,
    plan: "premium",
  },
  {
    id: "demo-tailor-modou",
    shop_name: "Modou Tailleur Moderne",
    bio: "Coupes modernes, costumes et chemises africaines sur mesure.",
    city: "Thiès",
    base_price: 12000,
    avg_delivery_days: 10,
    free_delivery: false,
    cover_url: img("modoutailleur"),
    rating: 4.6,
    rating_count: 89,
    is_active: true,
    is_suspended: false,
    suspension_reason: null,
    is_certified: false,
    plan: "free",
  },
  {
    id: "demo-tailor-awa",
    shop_name: "Awa Design & Broderie",
    bio: "Broderie fine et finitions luxe pour boubous et ensembles femme.",
    city: "Dakar",
    base_price: 20000,
    avg_delivery_days: 12,
    free_delivery: true,
    cover_url: img("awadesign"),
    rating: 4.9,
    rating_count: 154,
    is_active: true,
    is_suspended: false,
    suspension_reason: null,
    is_certified: true,
    plan: "standard",
  },
  {
    id: "demo-tailor-ibrahima",
    shop_name: "Ibrahima Sur Mesure",
    bio: "Grand boubou et kaftan traditionnels, travail soigné et rapide.",
    city: "Saint-Louis",
    base_price: 10000,
    avg_delivery_days: 6,
    free_delivery: false,
    cover_url: img("ibrahimacouture"),
    rating: 4.5,
    rating_count: 63,
    is_active: true,
    is_suspended: false,
    suspension_reason: null,
    is_certified: false,
    plan: "free",
  },
];

// Boutiques de tissu, pendant vendeur des tailleurs ci-dessus. Comme eux, chaque
// vendeur a une fiche publique (`/vendeurs/[id]`) : photo, présentation, ville,
// et la grille de ses tissus. Ces mêmes lignes servent aussi la vue admin
// (`DEMO_VENDORS` les réexporte).
export const VENDORS: Vendor[] = [
  {
    id: "demo-vendor-hlm",
    shop_name: "Tissus Marché HLM",
    bio: "Bazin riche, wax et getzner au cœur du plus grand marché de Dakar.",
    city: "Dakar",
    cover_url: img("marchehlm"),
    is_active: true,
    is_suspended: false,
    suspension_reason: null,
    is_certified: true,
    plan: "free",
  },
  {
    id: "demo-vendor-touba",
    shop_name: "Bazin & Wax Touba",
    bio: "Grossiste en bazin teinté main, spécialiste des grandes cérémonies.",
    city: "Touba",
    cover_url: img("bazintouba"),
    is_active: true,
    is_suspended: false,
    suspension_reason: null,
    is_certified: false,
    plan: "premium",
  },
  {
    id: "demo-vendor-khadi",
    shop_name: "Khadi Textiles",
    bio: "Lin, coton et soie importés, sélection haut de gamme pour le sur-mesure.",
    city: "Dakar",
    cover_url: img("khaditextiles"),
    is_active: true,
    is_suspended: false,
    suspension_reason: null,
    is_certified: false,
    plan: "standard",
  },
];

// Avis clients de démonstration, rattachés aux tailleurs ci-dessus. `author_name`
// est le nom de l'auteur, joint depuis `profiles` côté base ; ici il est en dur.
const daysAgo = (n: number) =>
  new Date(Date.now() - n * 24 * 3600 * 1000).toISOString();

export const REVIEWS: (Review & { author_name: string | null })[] = [
  {
    id: "demo-review-fatou-1",
    order_id: "demo-order-1019",
    client_id: "demo-client-bineta",
    tailor_id: "demo-tailor-fatou",
    rating: 5,
    comment:
      "Boubou impeccable, finitions soignées et livraison à l'heure. Merci !",
    created_at: daysAgo(16),
    author_name: "Bineta Gueye",
  },
  {
    id: "demo-review-fatou-2",
    order_id: "demo-order-1031",
    client_id: "demo-client-ndeye",
    tailor_id: "demo-tailor-fatou",
    rating: 5,
    comment:
      "Deuxième commande, toujours aussi satisfaite. Je recommande vivement.",
    created_at: daysAgo(3),
    author_name: "Ndeye Fall",
  },
  {
    id: "demo-review-modou-1",
    order_id: "demo-order-2065",
    client_id: "demo-client-pape",
    tailor_id: "demo-tailor-modou",
    rating: 4,
    comment:
      "Très bon travail, la coupe est parfaite. Un léger retard de deux jours.",
    created_at: daysAgo(14),
    author_name: "Pape Ndoye",
  },
  {
    id: "demo-review-awa-1",
    order_id: "demo-order-1028",
    client_id: "demo-client-ousmane",
    tailor_id: "demo-tailor-awa",
    rating: 5,
    comment: "La broderie est magnifique, exactement ce que je voulais.",
    created_at: daysAgo(9),
    author_name: "Ousmane Ba",
  },
  {
    id: "demo-review-ibrahima-1",
    order_id: "demo-order-1036",
    client_id: "demo-client-fatou",
    tailor_id: "demo-tailor-ibrahima",
    rating: 3,
    comment:
      "Kaftan correct mais le tissu fourni n'a pas été très bien repassé.",
    created_at: daysAgo(6),
    author_name: "Fatou Ndiaye",
  },
];
